window.ARTICLES = [
  { slug: 'rozlouceni',   title: 'ROZLOUČENÍ' },
  { slug: 'zivot',        title: 'ŽIVOT' },
  { slug: 'vira',         title: 'VÍRA' },
  { slug: 'respekt',      title: 'RESPEKT' },
  { slug: 'smrt',         title: 'SMRT' },
  { slug: 'myslenky',     title: 'MYŠLENKY' },
  { slug: 'zpravy',       title: 'ZPRÁVY' },
  { slug: 'tinder',       title: 'TINDER' },
  { slug: 'rozchod',      title: 'ROZCHOD' },
  { slug: 'zvyk',         title: 'ZVYK' },
  { slug: 'zkusenosti',   title: 'ZKUŠENOSTI' },
  { slug: 'minimalismus', title: 'MINIMALISMUS' },
  { slug: 'alkohol',      title: 'ALKOHOL' },
  { slug: 'bolest',       title: 'BOLEST' },
  { slug: 'ocekavani',    title: 'OČEKÁVÁNÍ' },
  { slug: 'osamocenost',  title: 'OSAMOCENOST' },
  { slug: 'media',        title: 'MÉDIA' },
  { slug: 'rakovina',     title: 'RAKOVINA' },
];
